### ISSUE TITLE
ERROR in node_modules/rxjs/operators/map.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/operators/map'

### ISSUE THREAD

**Issue by raitalharehman** [lwazevedo/adminlte-angular7#1]
error while running `npm start` tried `npm i`

**Comment by lwazevedo** [comment]
Hello @raitalharehman,

Sorry for my mistake. I just adjusted the same. If it persists please open a new issue.

**Comment by raitalharehman** [comment]
@lwazevedo thanks its working fine
